"""add status to orders

Revision ID: 5e11f580316b
Revises: 0006_frida_embedding_768
Create Date: 2026-01-16 14:44:08.632996

"""
import sqlalchemy as sa  # type: ignore

from alembic import op  # type: ignore

# revision identifiers, used by Alembic.
revision = '5e11f580316b'
down_revision = '0006_frida_embedding_768'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # 1. Добавляем колонку как nullable
    op.add_column('orders', sa.Column('status', sa.String(length=20), nullable=True))

    # 2. Устанавливаем 'draft' для существующих записей
    op.execute("UPDATE orders SET status = 'draft' WHERE status IS NULL")

    # 3. Делаем колонку NOT NULL
    op.alter_column('orders', 'status', nullable=False, server_default='draft')

    # 4. Пересоздаём индекс для embedding (размерность изменилась 256→1536)
    op.drop_index(op.f('idx_hardware_items_embedding'), table_name='hardware_items', postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_with={'lists': '100'}, postgresql_using='ivfflat', if_exists=True)
    op.create_index('idx_hardware_items_embedding', 'hardware_items', ['embedding'], unique=False, postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_with={'lists': '100'}, postgresql_using='ivfflat')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'status')
    op.create_index(op.f('idx_hardware_items_embedding'), 'hardware_items', ['embedding'], unique=False, postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_with={'lists': '100'}, postgresql_using='ivfflat')
    # ### end Alembic commands ###
