"""Add DialogueMessage model

Revision ID: d4e5372b9af5
Revises: b52b43cce1ca
Create Date: 2025-09-06 12:40:43.216658

"""
import sqlalchemy as sa  # type: ignore

from alembic import op  # type: ignore

# revision identifiers, used by Alembic.
revision = 'd4e5372b9af5'
down_revision = 'b52b43cce1ca'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dialogue_messages',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('order_id', sa.UUID(), nullable=False),
    sa.Column('turn_number', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column('cam_jobs', 'status',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.Enum('Created', 'Processing', 'Completed', 'Failed', name='job_status', native_enum=False),
               existing_nullable=False)
    op.drop_index(op.f('idx_hardware_items_embedding'), table_name='hardware_items', postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_with={'lists': '100'}, postgresql_using='ivfflat')
    op.drop_index(op.f('ix_hardware_items_embedding_ivfflat'), table_name='hardware_items', postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_with={'lists': '100'}, postgresql_using='ivfflat')
    op.alter_column('panels', 'product_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('validation_items', 'validation_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('validations', 'status',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.Enum('Pending', 'Approved', 'Rejected', name='validation_status', native_enum=False),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('validations', 'status',
               existing_type=sa.Enum('Pending', 'Approved', 'Rejected', name='validation_status', native_enum=False),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)
    op.alter_column('validation_items', 'validation_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('panels', 'product_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.create_index(op.f('ix_hardware_items_embedding_ivfflat'), 'hardware_items', ['embedding'], unique=False, postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_with={'lists': '100'}, postgresql_using='ivfflat')
    op.create_index(op.f('idx_hardware_items_embedding'), 'hardware_items', ['embedding'], unique=False, postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_with={'lists': '100'}, postgresql_using='ivfflat')
    op.alter_column('cam_jobs', 'status',
               existing_type=sa.Enum('Created', 'Processing', 'Completed', 'Failed', name='job_status', native_enum=False),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)
    op.drop_table('dialogue_messages')
    # ### end Alembic commands ###
